### ISSUE TITLE
PDroid Patch

### ISSUE THREAD

**Issue by TuxCoder** [M1cha/android_device_xiaomi_aries#31]
I have the issue, that when i use the openPDroid patch from autopatcher(v3.8.3), the com.android.systemui allways crache. At the moment I use cm11-20131229 and it works fine. I have also tried to wipe the data partition but it doesn't help.

I have a MI2.

**Comment by M1cha** [comment]
I don't know much about pdroid but if you don't use ART you can use XPosed framework + XPrivacy.
However I need crash logs(logcat) to tell u more about pdroid.

**Comment by TuxCoder** [comment]
Hello M1cha heres the logcat.
I don't know if this is a bug from the rom or from the pdroid patch:

```
/InputMethodManagerService(  638): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@41f696f0 attribute=null, token = android.os.BinderProxy@41e7fc30
W/InputDispatcher(  638): channel '41a101b8 com.android.systemui.ImageWallpaper (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  638): channel '41a101b8 com.android.systemui.ImageWallpaper (server)' ~ Channel is unrecoverably broken and will be disposed!
W/InputDispatcher(  638): Attempted to unregister already unregistered input channel '41a101b8 com.android.systemui.ImageWallpaper (server)'
I/ActivityManager(  638): Process com.android.systemui (pid 2796) has died.
I/StatusBarManagerService(  638): binder died for pkg=com.android.keyguard
W/ActivityManager(  638): Scheduling restart of crashed service com.android.systemui/.ImageWallpaper in 0ms
W/ActivityManager(  638): Scheduling restart of crashed service com.android.systemui/.SystemUIService in 0ms
W/WallpaperService(  638): Wallpaper service gone: ComponentInfo{com.android.systemui/com.android.systemui.ImageWallpaper}
W/ActivityManager(  638): Scheduling restart of crashed service com.android.keyguard/.KeyguardService in 0ms
I/WindowState(  638): WIN DEATH: Window{41a101b8 u0 com.android.systemui.ImageWallpaper}
I/ActivityManager(  638): Start proc com.android.systemui for restart com.android.systemui: pid=3684 uid=10008 gids={50008, 1028, 1015, 1035, 1006, 3002, 3001}
D/SystemUIService( 3684): loading: class com.android.systemui.recent.Recents
D/SystemUIService( 3684): running: com.android.systemui.recent.Recents@418bf8d0
D/SystemUIService( 3684): loading: class com.android.systemui.statusbar.SystemBars
D/SystemUIService( 3684): running: com.android.systemui.statusbar.SystemBars@418bfeb8
D/SystemUIService( 3684): loading: class com.android.systemui.usb.StorageNotification
D/SystemUIService( 3684): running: com.android.systemui.usb.StorageNotification@418c1e58
D/SystemUIService( 3684): loading: class com.android.systemui.power.PowerUI
D/SystemUIService( 3684): running: com.android.systemui.power.PowerUI@418c3678
D/SystemUIService( 3684): loading: class com.android.systemui.media.RingtonePlayer
D/SystemUIService( 3684): running: com.android.systemui.media.RingtonePlayer@418c49c0
D/SystemUIService( 3684): loading: class com.android.systemui.settings.SettingsUI
D/SystemUIService( 3684): running: com.android.systemui.settings.SettingsUI@418c5d80
I/StatusBarManagerService(  638): registerStatusBar bar=com.android.internal.statusbar.IStatusBar$Stub$Proxy@418e7c68
E/WimaxHelper( 3684):   at com.android.systemui.DockBatteryMeterView.<init>(DockBatteryMeterView.java:125)
E/WimaxHelper( 3684):   at com.android.systemui.DockBatteryMeterView.<init>(DockBatteryMeterView.java:120)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:536)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(PhoneStatusBar.java:2662)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.phone.PhoneStatusBar.createAndAddWindows(PhoneStatusBar.java:2636)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.BaseStatusBar.start(BaseStatusBar.java:316)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:468)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.SystemBars.createStatusBarFromConfig(SystemBars.java:106)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.SystemBars.onNoService(SystemBars.java:58)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.ServiceMonitor.startService(ServiceMonitor.java:228)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.ServiceMonitor.access$000(ServiceMonitor.java:49)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.ServiceMonitor$1.handleMessage(ServiceMonitor.java:73)
E/WimaxHelper( 3684):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/WimaxHelper( 3684):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
I/PrivacyConnectivityManager( 3684): now in constructor for package: com.android.keyguard
D/PrivacyPersistenceAdapter(  638): PrivacyPersistenceAdapter:getSettingsfound for package com.android.systemui
V/PDroidAlternative( 2205): NotificationHandler: Notification for: com.android.systemui:networkInfoCurrent:0
D/PrivacyPersistenceAdapter(  638): PrivacyPersistenceAdapter:getSettingsfound for package com.android.keyguard
V/PDroidAlternative( 2205): NotificationHandler: Notification for: com.android.keyguard:networkInfoCurrent:0
E/WimaxHelper( 3684):   at com.android.internal.util.cm.QSUtils.deviceSupportsDockBattery(QSUtils.java:72)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.phone.QuickSettingsController.loadDockBatteryTile(QuickSettingsController.java:336)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.phone.QuickSettingsController.loadTiles(QuickSettingsController.java:286)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.phone.QuickSettingsController.setupQuickSettings(QuickSettingsController.java:371)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:796)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(PhoneStatusBar.java:2662)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.phone.PhoneStatusBar.createAndAddWindows(PhoneStatusBar.java:2636)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.BaseStatusBar.start(BaseStatusBar.java:316)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:468)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.SystemBars.createStatusBarFromConfig(SystemBars.java:106)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.SystemBars.onNoService(SystemBars.java:58)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.ServiceMonitor.startService(ServiceMonitor.java:228)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.ServiceMonitor.access$000(ServiceMonitor.java:49)
E/WimaxHelper( 3684):   at com.android.systemui.statusbar.ServiceMonitor$1.handleMessage(ServiceMonitor.java:73)
E/WimaxHelper( 3684):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/WimaxHelper( 3684):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
E/AndroidRuntime( 3684): Process: com.android.systemui, PID: 3684
E/AndroidRuntime( 3684):        at com.android.internal.util.cm.QSUtils.deviceSupportsDockBattery(QSUtils.java:73)
E/AndroidRuntime( 3684):        at com.android.systemui.statusbar.phone.QuickSettingsController.loadDockBatteryTile(QuickSettingsController.java:336)
E/AndroidRuntime( 3684):        at com.android.systemui.statusbar.phone.QuickSettingsController.loadTiles(QuickSettingsController.java:286)
E/AndroidRuntime( 3684):        at com.android.systemui.statusbar.phone.QuickSettingsController.setupQuickSettings(QuickSettingsController.java:371)
E/AndroidRuntime( 3684):        at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:796)
E/AndroidRuntime( 3684):        at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(PhoneStatusBar.java:2662)
E/AndroidRuntime( 3684):        at com.android.systemui.statusbar.phone.PhoneStatusBar.createAndAddWindows(PhoneStatusBar.java:2636)
E/AndroidRuntime( 3684):        at com.android.systemui.statusbar.BaseStatusBar.start(BaseStatusBar.java:316)
E/AndroidRuntime( 3684):        at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:468)
E/AndroidRuntime( 3684):        at com.android.systemui.statusbar.SystemBars.createStatusBarFromConfig(SystemBars.java:106)
E/AndroidRuntime( 3684):        at com.android.systemui.statusbar.SystemBars.onNoService(SystemBars.java:58)
E/AndroidRuntime( 3684):        at com.android.systemui.statusbar.ServiceMonitor.startService(ServiceMonitor.java:228)
E/AndroidRuntime( 3684):        at com.android.systemui.statusbar.ServiceMonitor.access$000(ServiceMonitor.java:49)
E/AndroidRuntime( 3684):        at com.android.systemui.statusbar.ServiceMonitor$1.handleMessage(ServiceMonitor.java:73)
E/AndroidRuntime( 3684):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
E/AndroidRuntime( 3684):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
```

**Comment by TuxCoder** [comment]
Thanks for the tip with the XPrivacy app.
It has a lot of more setting than the PDroid patch.
